module.exports = {
  activate: function() {},
  consumeStatusBar: function(statusBar) {
    return this.statusBarTile = statusBar.addLeftTile({
      item: myElement,
      priority: 100
    });
  },
  deactivate: function() {
    var ref;
    if ((ref = this.statusBarTile) != null) {
      ref.destroy();
    }
    return this.statusBarTile = null;
  }
};

// ---
// generated by coffee-script 1.9.2
